// generator-jhipster-react/generators/react/templates/src/components/Ping.js
import React, { useState } from 'react';
<%_ if (oauth2) { _%>
import { useAuth } from "react-oidc-context";
<%_ } _%>

const PingDropdown = ({ onDropdownChange }) => {
    const [selectedValue, setSelectedValue] = useState('');

    const handleDropdownChange = (event) => {
        const newValue = event.target.value;
        setSelectedValue(newValue);
        onDropdownChange(newValue);
    };

    return (
        <div className="dropdownContainer">
            <select
                id="pingDropdown"
                value={selectedValue}
                onChange={handleDropdownChange}
                className="pingDropdown"
            >
                <option value="" className="dropdownOption">Select an option</option>
            <%_ for (let i = 0; i < servicesWithOutDB.length ; i++) { _%>
                <option value="<%= servicesWithOutDB[i].toLowerCase() %>" className="dropdownOption"><%= servicesWithOutDB[i].toLowerCase() %></option>
            <%_ } _%>
            </select>
        </div>
    );
};

const Ping = () => {
    const [selectedService, setSelectedService] = useState('');
    const [responseData, setResponseData] = useState(null);
    <%_ if (oauth2) { _%>
    const auth = useAuth();
    <%_ } _%>

    const handleDropdownChange = (value) => {
        setSelectedService(value);
    };

    const handlePing = () => {
        if (selectedService) {
            // Make the API call using fetch
            let envString = "REACT_APP_MICROSERVICE_" + selectedService.toUpperCase();
            fetch( process.env[envString] + `/api/services/${selectedService}`, {
                method: 'GET',
                headers: {
                    <%_ if (oauth2) { _%>
                    'Authorization': `Bearer ${auth.user.access_token}`,
                    <%_ } _%>
                    'Content-Type': 'application/json',
                }
            })
                .then(response => response.json())
                .then(data => {
                    // Set the response data in state
                    setResponseData(data.server);
                })
                .catch(error => {
                    // Handle errors
                    console.error('API Error:', error);
                });
        } else {
            console.error('Please select a service before pinging.');
            setResponseData("");
        }
    };

    return (
        <div className='container ping'>
            <h2 style={{ color: "black" }}> Ping your service</h2>
            <div className='select-service'>
                <h4 style={{ color: "black" }}>  Select Your service to be pinged</h4>
                <PingDropdown onDropdownChange={ handleDropdownChange } />
                <button className='ping-button' onClick={ handlePing }>
                    Ping
                </button>
                <div>
                    <label style={{ color: 'black' }}>Response body</label>
                    <div className='response-container'>
                        <h6>{responseData ? '{\n\t"server": "' + responseData + '"\n}' : 'No response yet'}</h6>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Ping;

// generator-jhipster-angular/generators/angular/templates/src/app/ping/ping.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient , HttpHeaders } from '@angular/common/http';
import { environment } from '../../../environment';
<%_ if(oauth2)  { _%>
import { OidcSecurityService } from 'angular-auth-oidc-client';
<%_ } _%> 

@Component({
  selector: 'app-ping',
  templateUrl: './ping.component.html',
  styleUrls: ['./ping.component.css']
})
export class PingComponent implements OnInit {
  
  selectedService: string = '';
  responseData: any = null;
  
  constructor(private http: HttpClient,
    <%_ if(oauth2)  { _%>
    private authService: OidcSecurityService,
    <%_ } _%> 
    ) {
    console.log('PingComponent initialized');
  }

  ngOnInit(): void {
    console.log('PingComponent ngOnInit');
  }

  handleDropdownChange(value: string): void {
    this.selectedService = value;
  }

  handlePing(): void {
    if (this.selectedService) {
      let selectedServiceEnv = "microservice" + this.selectedService.charAt(0).toUpperCase() + this.selectedService.slice(1);
      let apiUrl: string | undefined;
      const environmentKeyAndValuePairs: { key: string; value: string }[] = Object.keys(environment).map((key) => ({
        key,
        value: environment[key as keyof typeof environment], // Type assertion here
      }));
      const foundEnv = environmentKeyAndValuePairs.find((pair) => pair.key.toLowerCase() === selectedServiceEnv.toLowerCase());
      if (foundEnv) {
        apiUrl = foundEnv.value;
      }
      <%_ if(oauth2)  { _%>
      const authTokenObservable = this.authService.getAccessToken();
      authTokenObservable.subscribe((token: string) => {
      const headers = new HttpHeaders().set('Authorization', `Bearer ${token}`);
      <%_ } _%> 
      // Make the API call using Angular HttpClient
      this.http.get<any>(apiUrl + `/api/services/${this.selectedService}`,
      <%_ if(oauth2)  { _%> 
      { headers }
       <%_ } _%> 
       ).subscribe(
        data => {
          // Set the response data in component property
          this.responseData = data.server;
        },
        error => {
          // Handle errors
          console.error('API Error:', error);
        }
      );
      <%_ if(oauth2)  { _%>
    });
    <%_ } _%> 
    } else {
      console.error('Please select a service before pinging.');
      this.responseData = '';
    }
  }
}

<div class="ping">
    <h2 style="color: black;">Ping your service</h2>
    <div class="select-service">
      <h4 style="color: black;">Select Your service to be pinged</h4>
      <!-- Simple dropdown list directly in the component -->
      <select
      id="pingDropdown"
      [(ngModel)]="selectedService"
      class="pingDropdown"
    >
        <option value="">Select an option</option>
        <%_ for (let i = 0; i < servicesWithOutDB.length ; i++) { _%>
        <option value="<%= servicesWithOutDB[i].toLowerCase() %>"><%= servicesWithOutDB[i].toLowerCase() %></option>
      <%_ } _%>
      </select>
      <button class="ping-button" (click)="handlePing()" style="font-size: medium; cursor: pointer;">Ping</button>
      <div>
        <label style="color: rgb(0, 0, 0);">Response body</label>
        <div class="response-container" style="color: rgb(255, 255, 255);">
          <!-- Use Angular syntax for property binding -->
          <h4 >{{ responseData ? '{\n\t"server": "' + responseData + '"\n}' : 'No response yet' }}</h4>
        </div>
      </div>
    </div>
  </div>
