// generator-jhipster-angular/generators/angular/templates/src/app/layouts/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { LoginResponse, OidcSecurityService } from 'angular-auth-oidc-client';
import { environment } from '../../../../environment';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
})
export default class NavbarComponent implements OnInit {
  isNavbarCollapsed = true;
  isAuthenticated: boolean = false;
  private isAuthenticatedSubscription!: Subscription;

  constructor(private router: Router, public oidcSecurityService: OidcSecurityService) {
    this.isAuthenticated = false; // Initialize as false initially
  }

  ngOnInit(): void {
    this.isAuthenticatedSubscription = this.oidcSecurityService.isAuthenticated$.subscribe({
      next: result => {
        this.isAuthenticated = result.isAuthenticated;
      },
    });
    window.addEventListener('scroll', this.onScroll);
  }

  openDocs(): void {
    window.open(environment.wedaaDocs, '_blank');
  }

  openGit(): void {
    window.open(environment.wedaaGithub, '_blank');
  }

  toggleNavbar(): void {
    this.isNavbarCollapsed = !this.isNavbarCollapsed;
  }
  public activeLink = 'home';
  public scrolled = false;
  public isSubMenuOpen = false;
  public isloggedIn = false;

  ngOnDestroy(): void {
    this.isAuthenticatedSubscription.unsubscribe();

    window.removeEventListener('scroll', this.onScroll);
  }

  onScroll = () => {
    this.scrolled = window.scrollY > 50;
  };

  updateActiveLink(link: string): void {
    this.activeLink = link;
  }

  openLink(link: string): void {
    window.open(link, '_blank');
  }

  login() {
    this.oidcSecurityService.authorize();
  }

  logout() {
    this.oidcSecurityService
      .logoff()
      .subscribe((result) => console.log(result));
    window.location.href = environment.projectUrl; 
  }
}

<nav class="navbar">
  <div class="container">
    <a class="navbar-brand" href="/"></a>
    <div class="navbar-collapse" id="basic-navbar-nav">
      <div class="nav-options">
        <div class="navbar-nav ms-auto">
          <span class="nav-item">
            <a href="/" class="nav-link-home">Home</a>
          </span>
          <%_  if ( apiServers.length > 0 ) { _%> 
            <div class="nav-item" (click)="openSwaggerDropdown()">
              <a class="nav-link">Swagger ˅ </a>
              <app-dropdown [isOpen]="isSwaggerDropdownOpen"></app-dropdown>
            </div>
          <%_ } _%> 
          <%_  if ( servicesWithOutDB.length > 0 ) { _%> 
          <span class="nav-item">
            <a routerLink="/ping" class="nav-link">Ping</a>
          </span>
          <%_ } _%>  
          <span class="nav-item">
            <a (click)="openDocs()" class="nav-link">Docs</a>
          </span>
        </div>

        <span class="navbar-text">
          <span class="social-icon">
            <a class="nav-link" (click)="openGit()">
              <svg width="28" height="28" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path
                  fill="#fff"
                  d="M12 2.247a10 10 0 0 0-3.162 19.487c.5.088.687-.212.687-.475c0-.237-.012-1.025-.012-1.862c-2.513.462-3.163-.613-3.363-1.175a3.636 3.636 0 0 0-1.025-1.413c-.35-.187-.85-.65-.013-.662a2.001 2.001 0 0 1 1.538 1.025a2.137 2.137 0 0 0 2.912.825a2.104 2.104 0 0 1 .638-1.338c-2.225-.25-4.55-1.112-4.55-4.937a3.892 3.892 0 0 1 1.025-2.688a3.594 3.594 0 0 1 .1-2.65s.837-.262 2.75 1.025a9.427 9.427 0 0 1 5 0c1.912-1.3 2.75-1.025 2.75-1.025a3.593 3.593 0 0 1 .1 2.65a3.869 3.869 0 0 1 1.025 2.688c0 3.837-2.338 4.687-4.563 4.937a2.368 2.368 0 0 1 .675 1.85c0 1.338-.012 2.413-.012 2.75c0 .263.187.575.687.475A10.005 10.005 0 0 0 12 2.247Z"
                />
              </svg>
            </a>
          </span>
        <%_ if(oauth2)  { _%>
          <div *ngIf="!isAuthenticated">
            <button class="vvd" (click)="login()" id="login" data-cy="login">
              <span>Sign In</span>
            </button>
          </div>
          <div *ngIf="isAuthenticated">
            <button class="vvd" (click)="logout()"id="logout" data-cy="logout">
              <span>Sign Out</span>
            </button>
          </div>
        <%_ } _%>  
        </span>
      </div>
    </div>
  </div>
</nav>

// generator-jhipster-nextjs/generators/app/templates/src/app/components/NavBar.jsx
'use client';

import { useState, useEffect } from "react";
import { Navbar, Nav, Container } from "react-bootstrap";
import { BiChevronDown } from 'react-icons/bi';
<%_ if(oauth2) { _%>
  import { useSession,signIn, signOut } from "next-auth/react";
<%_ } _%>


export const NavBar = () => {

  const [activeLink, setActiveLink] = useState('home');
  const [scrolled, setScrolled] = useState(false);
  const [isSubMenuOpen, setIsSubMenuOpen] = useState(false);
  <%_  if( servicesWithDB.length > 0 ) { _%>
    const [isSubMenuOpenForNotes, setIsSubMenuOpenForNotes] = useState(false);
  <%_ } _%> 
  <%_ if(oauth2) { _%>
    const [isLoggedIn,setIsLoggedIn] = useState(false);
  <%_ } _%>


  <%_ if (oauth2) { _%>
    const authData = useSession();
  <%_ } _%> 

  useEffect(() => {
    const onScroll = () => {
      if (window.scrollY > 50) {
        setScrolled(true);
      } else {
        setScrolled(false);
      }
    }

    window.addEventListener("scroll", onScroll);

    return () => window.removeEventListener("scroll", onScroll);
  }, [])

  <%_ if (oauth2) { _%>

    useEffect(()=>{
      if (authData.status==='loading') {
        return <></>;
      }
      else if(authData.status==='unauthenticated'){
        setIsLoggedIn(false);
      }
      else if (authData.status==='authenticated') {
        setIsLoggedIn(true);
      }
    },[authData]);
    
  <%_ } _%> 

  const toggleMenu = () => {
    console.log("Toggle menu swagger clicked");
    setIsSubMenuOpen(!isSubMenuOpen);
  }
  
  <%_  if( servicesWithDB.length > 0 ) { _%>
    const toggleNotesMenu = () => {
      console.log("Toggle menu notes clicked");
      setIsSubMenuOpenForNotes(!isSubMenuOpenForNotes);
  
    }
  <%_ } _%> 


  const onUpdateActiveLink = (value) => {
    console.log("Update active link clicked");
    setActiveLink(value);
  }

  



  return (
      <Navbar expand="md" className={scrolled ? "scrolled" : ""}>
        <Container>
          <Navbar.Brand href="/">
          </Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav">
            <span className="navbar-toggler-icon"></span>
          </Navbar.Toggle>
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="ms-auto">
              <Nav.Link href="/" 
                className={activeLink === 'home' ? 'active navbar-link' : 'navbar-link'} onClick={() => onUpdateActiveLink('home')}>
                  Home
              </Nav.Link>
       
              <%_  if(apiServers.length > 0) { _%>
              <Nav.Link
                className={activeLink === 'skills' ? 'active navbar-link' : 'navbar-link'}
                onClick={() => {
                  toggleMenu();
                  onUpdateActiveLink('skills');
                }}>
                  Swagger <BiChevronDown />
              </Nav.Link>  
            <%_ } _%> 
     
          
     <%_  if( servicesWithOutDB.length > 0 ) { _%>
              <Nav.Link
                href="/ping"
                className={activeLink === 'ping' ? 'active navbar-link' : 'navbar-link'}
                onClick={() => onUpdateActiveLink('ping')}
              >
                Ping
              </Nav.Link>
            <%_ } _%>  


      
<%_  if( servicesWithDB.length > 0 ) { _%>
              <Nav.Link
                className={
                  activeLink === "notes" ? "active navbar-link" : "navbar-link"
                }
                onClick={() => {
                  toggleNotesMenu();
                  onUpdateActiveLink("notes")
                }}
              >
                Notes <BiChevronDown />
            </Nav.Link>
            <%_ } _%> 

    

              <Nav.Link href="/docs" 
                className={activeLink === 'projects' ? 'active navbar-link' : 'navbar-link'} onClick={() => onUpdateActiveLink('projects')}>
                  Docs
              </Nav.Link>
            </Nav>
       
            <%_  if (apiServers.length > 0) { _%>
            <div className={isSubMenuOpen ? "sub-menu-wrap open-menu" : "sub-menu-wrap"} id="subMenu">
              <div className="sub-menu">
              <%_  if (apiServers.length == 1) { _%>
                <a href="/swagger/<%= apiServers[0].baseName.toLowerCase() %>" className="sub-menu-link">
                  <img src=""></img>
                  <h5><%= apiServers[0].baseName.toLowerCase() %></h5>
                  <span>&gt;</span>
                </a>
                <hr></hr>
                <span></span>
              <%_ } else {_%> 
                <%_ for (let i = 0; i < apiServers.length - 1; i++) { _%>
                  <a href="/swagger/<%= apiServers[i].baseName.toLowerCase() %>" className="sub-menu-link">
                    <img src=""></img>
                    <h5><%= apiServers[i].baseName.toLowerCase() %></h5>
                    <span>&gt;</span>
                  </a>
                  <hr></hr>
                  <span></span>
                  <%_ } _%>
                <a href="/swagger/<%= apiServers[apiServers.length - 1].baseName.toLowerCase() %>" className="sub-menu-link">
                  <img src=""></img>
                  <h5><%= apiServers[apiServers.length - 1].baseName.toLowerCase() %></h5>
                  <span>&gt;</span>
                </a>
              <%_ } _%> 
              </div>
            </div>
          <%_ } _%> 

          <%_  if( servicesWithDB.length > 0 ) { _%>
            <div
                className={
                  isSubMenuOpenForNotes ? "sub-menu-wrap open-menu" : "sub-menu-wrap"
                }
                id="subMenu"
            >
              <div className="sub-menu">
                <%_  if (servicesWithDB.length == 1) { _%>
                <a href="/notes/<%= servicesWithDB[0].toLowerCase() %>" className="sub-menu-link">
                  <img src=""></img>
                  <h5><%= servicesWithDB[0].toLowerCase() %></h5>
                  <span>&gt;</span>
                </a>
                <hr></hr>
                <span></span>
                <%_ } else {_%> 
                  <%_ for (let i = 0; i < servicesWithDB.length - 1; i++) { _%>
                  <a href="/notes/<%= servicesWithDB[i].toLowerCase() %>" className="sub-menu-link">
                  <img src=""></img>
                  <h5><%= servicesWithDB[i].toLowerCase() %></h5>
                  <span>&gt;</span>
                  </a>
                  <hr></hr>
                  <span></span>
                  <%_ } _%> 
                  <a href="/notes/<%= servicesWithDB[servicesWithDB.length - 1].toLowerCase() %>" className="sub-menu-link">
                  <img src=""></img>
                  <h5><%= servicesWithDB[servicesWithDB.length - 1].toLowerCase() %></h5>
                  <span>&gt;</span>
                </a>
              <%_ } _%> 
              </div>
            </div>
          <%_ } _%>  

            <span className="navbar-text">
              <div className="social-icon">
                <a href={process.env.WEDAA_GITHUB}><img src="/assets/img/nav-icon2.svg" alt="" /></a>
              </div>
            <%_ if (oauth2) { _%>
              {isLoggedIn ? (
                <a target="_blank" rel="noopener noreferrer">
                  <button className="vvd" onClick={() => {
                    signOut()
                  }
                  }>
                    <span>Sign Out</span>
                  </button>
                </a>
              ) :
                <a target="_blank" rel="noopener noreferrer">
                  <button className="vvd" onClick={() => {signIn(['keycloak'])}}>
                    <span>Sign In</span>
                  </button>
                </a>
              }
            <%_ } _%> 
            </span>
          </Navbar.Collapse>
        </Container>
      </Navbar>
  )
}
